CREATE DATABASE IF NOT EXISTS SIMS;
USE SIMS;

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(100) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS spare_parts (
  id INT AUTO_INCREMENT PRIMARY KEY,
  spare_name VARCHAR(150) NOT NULL,
  category VARCHAR(100) NOT NULL,
  unit VARCHAR(50) NOT NULL,
  
  minimum_quantity INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS stock_in (
  id INT AUTO_INCREMENT PRIMARY KEY,
  spare_part_id INT NOT NULL,
  quantity INT NOT NULL,
  supplier VARCHAR(150) NOT NULL,
  stock_in_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_stock_in_spare
    FOREIGN KEY (spare_part_id) REFERENCES spare_parts(id)
    ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS stock_out (
  id INT AUTO_INCREMENT PRIMARY KEY,
  spare_part_id INT NOT NULL,
  quantity INT NOT NULL,
  destination VARCHAR(150) NOT NULL,
  stock_out_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_stock_out_spare
    FOREIGN KEY (spare_part_id) REFERENCES spare_parts(id)
    ON DELETE CASCADE
);
